GorestoBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
