GorestoBundle\Entity\Restaurant:
    type: entity
    table: restaurant
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryId:
            type: bigint
            nullable: false
            unsigned: false
            column: category_id
        email:
            type: string
            nullable: false
            length: 255
            fixed: true
        password:
            type: string
            nullable: true
            length: 128
            fixed: true
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
