GorestoBundle\Entity\UserOrderMenu:
    type: entity
    table: user_order_menu
    id:
        userOrderId:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: user_order_id
        menuId:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: menu_id
    fields:
        currencyId:
            type: bigint
            nullable: false
            unsigned: false
            column: currency_id
        price:
            type: decimal
            nullable: false
            precision: 6
            scale: 2
        quantity:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }
