GorestoBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            fixed: true
        password:
            type: string
            nullable: true
            length: 128
            fixed: true
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
        lastname:
            type: string
            nullable: false
            length: 255
            fixed: false
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
