GorestoBundle\Entity\UserOrder:
    type: entity
    table: user_order
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: false
            unsigned: false
            column: user_id
        restaurantAddressId:
            type: bigint
            nullable: false
            unsigned: false
            column: restaurant_address_id
        currencyId:
            type: bigint
            nullable: false
            unsigned: false
            column: currency_id
        price:
            type: decimal
            nullable: false
            precision: 6
            scale: 2
        type:
            type: string
            nullable: false
            length: 1
            fixed: true
        time:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
        line1:
            type: string
            nullable: true
            length: 255
            fixed: false
        line2:
            type: string
            nullable: true
            length: 255
            fixed: false
        locality:
            type: string
            nullable: true
            length: 255
            fixed: false
        region:
            type: string
            nullable: true
            length: 255
            fixed: false
        zipcode:
            type: string
            nullable: true
            length: 255
            fixed: false
        country:
            type: string
            nullable: true
            length: 255
            fixed: false
        telephone:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
